# Ensure that we only run CI test on the Node.js enabled servers.
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "5"

# Create a Travis memcached enabled environment for the test suite to run in and
# ensure that we test against localhost on Travis-CI.
services: memcache
env: MEMCACHED__HOST=localhost

# The `sevices: memcache` will start a memcached service on localhost
# and on the default port, but in order to test against multiple memcached
# instances we need to spawn a couple more, so we do that during the before
# script
before_script:
  - memcached -p 11212 -d
  - memcached -p 11213 -d

# Fix broken builds caused by packages using the carrot semver bullshit.
before_install:
  - "npm install -g npm@2.1.x"

