# ensure that we only run ci test on the Node.js enabled servers
language: node_js
node_js:
  - 0.8

# create a travis enabled environment for the test suite to run in
script: "make travisci"
services: memcache

# the `sevices: memcache` will start a memcached service on localhost
# and on the default port, but in order to test against multiple memcache
# instances we need to spawn a couple more, so we do that during the before
# script
before_script:
  - memcached -p 11212 -d
  - memcached -p 11213 -d
